# Generated by Django 4.0.1 on 2022-01-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_categories_profile_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
