# Generated by Django 4.0.1 on 2022-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_alter_categories_parentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('number', 'number'), ('select', 'select'), ('date', 'date'), ('text', 'text')], default=1, max_length=100)),
                ('isConfigurable', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
