# Generated by Django 4.0.1 on 2022-01-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0010_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=100)),
                ('option_value', models.CharField(max_length=100)),
                ('option_position', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='attributes',
            name='options',
            field=models.ManyToManyField(to='mobile.AttributeOption'),
        ),
    ]
