# Generated by Django 4.0.1 on 2022-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_attributeoption_attributes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='attributeFamilys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('family_attribute', models.ManyToManyField(to='mobile.Attributes')),
            ],
        ),
    ]
