# Generated by Django 4.0.1 on 2022-01-23 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_attributefamilys'),
    ]

    operations = [
        migrations.CreateModel(
            name='productAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=200)),
                ('attributeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile.attributes')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200, unique=True)),
                ('sku', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField()),
                ('meta_title', models.TextField()),
                ('meta_tags', models.TextField()),
                ('meta_description', models.TextField()),
                ('product_price', models.FloatField()),
                ('inventory', models.SmallIntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='mobile.Categories')),
                ('familyAtrributeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.attributes')),
                ('parentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.products')),
                ('productAttribute', models.ManyToManyField(to='mobile.productAttribute')),
                ('relatedProducts', models.ManyToManyField(to='mobile.Products')),
            ],
        ),
    ]
